'use strict';
(() => {
const $=id=>document.getElementById(id), W=58,H=23, SAVE='ascicat.bramble.v1';
const ABC='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const MORSE={A:'.-',B:'-...',C:'-.-.',D:'-..',E:'.',F:'..-.',G:'--.',H:'....',I:'..',J:'.---',K:'-.-',L:'.-..',M:'--',N:'-.',O:'---',P:'.--.',Q:'--.-',R:'.-.',S:'...',T:'-',U:'..-',V:'...-',W:'.--',X:'-..-',Y:'-.--',Z:'--..'};
function cipher(text,type,key=3){text=text.toUpperCase();if(type==='caesar')return text.replace(/[A-Z]/g,c=>ABC[(ABC.indexOf(c)+key)%26]);if(type==='atbash')return text.replace(/[A-Z]/g,c=>ABC[25-ABC.indexOf(c)]);if(type==='numbers')return text.split(' ').map(w=>[...w].filter(c=>ABC.includes(c)).map(c=>ABC.indexOf(c)+1).join('-')).join(' / ');if(type==='morse')return text.split(' ').map(w=>[...w].filter(c=>ABC.includes(c)).map(c=>MORSE[c]).join(' ')).join(' / ');if(type==='reverse')return [...text].reverse().join('');if(type==='vigenere'){let i=0;return text.replace(/[A-Z]/g,c=>ABC[(ABC.indexOf(c)+ABC.indexOf('CAT'[i++%3]))%26]);}return text;}
const cats=[
{id:'pip',name:'Pip',glyph:'a',room:'foyer',x:35,y:13,type:'caesar',key:3,plain:'WORD ONE IS WHEN',word:'WHEN',slot:0,personality:'An orange kitten with a crooked whisker. He greets you as if you are late for an appointment.',tell:'Every letter is three little pawsteps ahead.',pet:'Pip rolls onto his back. It is, of course, a trap. A very soft trap.',after:'Pip chirps proudly. One word closer to the little voice below.'},
{id:'ink',name:'Ink',glyph:'b',room:'library',x:31,y:12,type:'atbash',plain:'WORD TWO IS THE',word:'THE',slot:1,personality:'A black kitten sits on a book titled HOW TO BE MYSTERIOUS. Upside down.',tell:'The alphabet looks different in a mirror.',pet:'Ink accepts your tribute with the dignity of a tiny librarian.',after:'Ink closes the book. Apparently you have passed the reading test.'},
{id:'biscuit',name:'Biscuit',glyph:'c',room:'dining',x:38,y:14,type:'numbers',plain:'WORD THREE IS MOON',word:'MOON',slot:2,personality:'A round kitten counts the silver forks. There are definitely fewer than there were yesterday.',tell:'A is one. Z is twenty-six. Counting is easier without mittens.',pet:'Biscuit smells faintly of stolen toast.',after:'Biscuit nods, then resumes an extremely suspicious fork inventory.'},
{id:'fern',name:'Fern',glyph:'d',room:'conservatory',x:23,y:13,type:'reverse',plain:'WORD FOUR IS SLEEPS',word:'SLEEPS',slot:3,personality:'A green-eyed kitten watches raindrops crawl down the glass. She has never seen a plant she cannot sit in.',tell:'Start where a sentence ends. Walk backwards.',pet:'Fern purrs so loudly that the ferns seem to vibrate.',after:'Fern blinks slowly. Even the garden needs to rest.'},
{id:'echo',name:'Echo',glyph:'e',room:'music',x:35,y:13,type:'morse',plain:'WORD FIVE IS WE',word:'WE',slot:4,personality:'A silver kitten taps one paw on a piano key: short, long, short.',tell:'Little taps are dots. Long taps are dashes. A slash means a new word.',pet:'Echo produces a purr in a surprisingly respectable musical key.',after:'Echo plays a small, triumphant chord. Mostly by sitting on it.'},
{id:'moth',name:'Moth',glyph:'f',room:'attic',x:36,y:13,type:'vigenere',plain:'WORD SIX IS PURR',word:'PURR',slot:5,personality:'A pale kitten emerges from a hatbox. Her collar reads CAT, CAT, CAT.',tell:'Repeat the key CAT. A=0, B=1. Subtract the key from each letter.',pet:'Moth disappears into your sleeve, then reappears as if nothing happened.',after:'Moth twitches her whiskers. You now know the last word.'},
{id:'ash',name:'Ash',glyph:'g',room:'hall',x:39,y:12,type:'caesar',key:5,plain:'THE KEY HIDES IN THE BEDROOM PILLOW',answer:'BEDROOM PILLOW',personality:'A smoky kitten patrols the hall like a very small security guard.',tell:'Five pawsteps forward to speak. Five back to listen.',pet:'Ash checks your hand for contraband, then leans into it.',after:'Ash glances upstairs. Somebody is sleeping on the job.'},
{id:'velvet',name:'Velvet',glyph:'h',room:'gallery',x:18,y:13,type:'atbash',plain:'BRING A LAMP TO THE CELLAR',answer:'LAMP',personality:'A white kitten poses beneath an oil painting of a much larger white kitten.',tell:'A faces Z. B faces Y. Velvet is very fond of symmetry.',pet:'Velvet stretches one immaculate paw. You may admire it.',after:'Velvet flicks her tail toward the kitchen. It gets dark downstairs.'}
].map(c=>({...c,encoded:cipher(c.plain,c.type,c.key)}));
const rooms={
foyer:{name:'The Foyer',floor:'GROUND FLOOR',flavor:'Rain threads the windows. A grandfather clock has stopped at nine. The welcome mat says PLEASE WIPE YOUR PAWS.',exits:{n:'hall'},props:[[6,4,['+-------+','|  9:00 |','|   o   |','|  /|\\  |','+-------+']],[39,5,['  /\\    /\\',' (  )  (  )','  ||    ||']],[20,17,['+---------------+','| WIPE YOUR PAWS|','+---------------+'],false]],clues:[{x:14,y:8,id:'album',name:'family album',text:'Nine names in a family album: Pip, Ink, Biscuit, Fern, Echo, Moth, Ash, Velvet... and Button. The ninth portrait is almost too small for its frame.'}]},
hall:{name:'The Long Hall',floor:'GROUND FLOOR',flavor:'The floorboards creak in sentences. Portraits of cats follow you with their eyes. Someone has sharpened their claws on history.',exits:{s:'foyer',w:'library',e:'dining',n:'gallery'},props:[[9,4,['[ /\\_/\\ ]','[( -.- )]']],[38,4,['[ /\\_/\\ ]','[( o.o )]']],[20,9,['::::::::::::::::::','::::::::::::::::::','::::::::::::::::::','::::::::::::::::::','::::::::::::::::::','::::::::::::::::::'],false]],clues:[]},
library:{name:'The Library',floor:'WEST WING',flavor:'Books from floor to ceiling. Almost every title contains the word fish. A bookmark moves by itself. Probably.',exits:{e:'hall',n:'conservatory'},props:[[5,4,['+----------+','|[]|[]||[]||','|[]||[]|[]||','+----------+']],[40,4,['+----------+','|[]|[]||[]||','|[]||[]|[]||','+----------+']],[12,15,['+-----------+','|  OPEN BOOK|','+-----------+']],[42,16,[' /---\\',' |___|',' /   \\']]],clues:[{x:18,y:14,id:'book',name:'marginal note',text:'A note in the margin: Six numbered words open the nursery below. Different kittens keep different words. The order matters.'}]},
dining:{name:'The Dining Room',floor:'EAST WING',flavor:'Nine saucers surround a table set for an unusually formal dinner. One saucer remains untouched.',exits:{w:'hall',n:'kitchen'},props:[[17,7,['  o    o    o    o','+--------------------+','|  ()  ()  ()  ()    |','|                    |','|  ()  ()  ()  ()  ()|','+--------------------+','  o    o    o    o']],[43,17,['+-----+','|/////|','+-----+']]],clues:[{x:14,y:15,id:'saucer',name:'empty saucer',text:'Button\'s saucer is untouched. A few threads of soft blue wool lead toward the gallery stairs.'}]},
kitchen:{name:'The Kitchen',floor:'EAST WING',flavor:'The oven is warm. A kettle mutters to itself. Tiny floury pawprints disappear under the cupboards.',exits:{s:'dining'},props:[[6,4,['+-----------------+','| O O | SINK | [] |','+-----------------+']],[38,4,['+----------+','| JARS JARS|','+----------+']],[13,14,['+----------+','|  (MILK)  |','+----------+']],[41,12,['  .-.','  |*|',' _|_|_']]],clues:[{x:43,y:15,id:'lamp',name:'storm lamp',item:'lamp',text:'You take the storm lamp. Its amber light makes the house feel a little less enormous.'},{x:16,y:18,id:'milk',name:'milk bowl',text:'A bowl of warm milk. You leave it for the cats. This earns you an invisible but important point.'}]},
gallery:{name:'The Portrait Gallery',floor:'UPPER FLOOR',flavor:'Moonlight turns the portraits silver. A little staircase spirals down through the floor. The air smells of old velvet.',exits:{s:'hall',w:'music',e:'bedroom',n:'attic'},props:[[8,4,['+---------+','| /\\_/\\  |','|( =.= )  |','+---------+']],[40,4,['+---------+','|  /\\_/\\ |','| ( o.o ) |','+---------+']],[26,16,['+-----+','| v v |','| v v |','+-----+']]],clues:[{x:29,y:17,id:'stairs',name:'cellar staircase',text:'An iron gate guards the cellar. A small brass keyhole glints beside the steps.'}]},
music:{name:'The Music Room',floor:'WEST UPSTAIRS',flavor:'An old piano is missing precisely one key. A metronome ticks even though nobody wound it. Short. Long. Short.',exits:{e:'gallery'},props:[[8,5,['+--------------+','|  GRAND PIANO |','|_|_|_|_|_|_|_||','|______________|',' |            |']],[39,5,['   /\\','  /..\\',' /____\\','   ||']],[14,16,[' ( )   ( )','  |     |',' / \\   / \\']]],clues:[]},
bedroom:{name:'The Blue Bedroom',floor:'EAST UPSTAIRS',flavor:'The bed is impossibly large. The pillow is suspiciously lumpy. The wardrobe is full of identical blue scarves.',exits:{w:'gallery'},props:[[34,5,['+----------------+','| [____] [____]  |','|----------------|','| ~~~~~~~~~~~~~~ |','| ~~~~~~~~~~~~~~ |','+----------------+']],[8,4,['+---------+','|   |  o  |','|   |     |','+---------+']],[11,16,['+-------+','| SCARF |','+-------+']]],clues:[{x:51,y:6,id:'key',name:'bedroom pillow',item:'key',text:'Under the pillow: a tiny brass key. Its bow is shaped like a sleeping kitten.'}]},
attic:{name:'The Attic',floor:'UNDER THE ROOF',flavor:'Dust drifts through a moonbeam. Hatboxes, trunks, forgotten birthdays. The roof sighs whenever the wind changes its mind.',exits:{s:'gallery'},props:[[6,5,['+---------+','| LETTERS |','+---------+']],[42,5,['  .----.',' / HATS \\',' |______|']],[8,15,['+------+  +------+','| 1891 |  | 1902 |','+------+  +------+']],[40,17,['  /\\',' /  \\','/____\\']]],clues:[{x:19,y:8,id:'collar',name:'old collar',text:'An old collar bears three letters: CAT. A note says to repeat them over and over. Moth seems very pleased you noticed.'}]},
conservatory:{name:'The Conservatory',floor:'BEYOND THE LIBRARY',flavor:'Rain drums softly on the glass roof. Ferns have colonized every available surface, including several unavailable ones.',exits:{s:'library'},props:[[8,4,['  \\|/    \\|/',' --*--  --*--','  /|\\    /|\\','  [_]    [_]']],[38,4,['   /\\','  /()\\',' /()()\\','   ||','  [__]']],[40,14,[' \\ | /','--\"\"--',' / | \\','  [_]']],[9,15,['+---------+','|  BENCH  |','+---------+']]],clues:[{x:44,y:12,id:'plant',name:'scratched flowerpot',text:'Scratched into a flowerpot: In the house, all things circle back. Even words. Even wandering humans.'}]},
cellar:{name:'The Cellar',floor:'BENEATH THE HOUSE',flavor:'The storm lamp catches on rows of dusty bottles. Beyond a small door, you hear the softest sound in the world.',exits:{s:'gallery',n:'vault'},props:[[5,5,['+----------+','|o o o o o |','|o o o o o |','+----------+']],[42,5,['+----------+','|o o o o o |','|o o o o o |','+----------+']],[8,16,['  (___)  (___)','  |   |  |   |','  (___)  (___)']],[25,3,['+-------+','|  ???  |','+-------+']]],clues:[{x:29,y:6,id:'gate',name:'whispering door',text:'Six empty spaces are carved above the lock. This door is listening.'}]},
vault:{name:'The Secret Nursery',floor:'THE HOUSE\'S HEART',flavor:'Nine kittens. A nest of blue scarves. You have found the smallest secret in the biggest house.',exits:{s:'cellar'},props:[[19,7,['  /~~~~~~~~~~~~~~~~\\',' /  BLUE SCARF NEST  \\','|       /\\_/\\        |','|      ( u.u )       |','|       > ^ <        |',' \\__________________/']],[8,16,[' () () () ()'],false],[36,16,[' () () () ()'],false]],clues:[{x:29,y:14,id:'button',name:'Button',text:'Button blinks up at you, then curls into a comma. Nine kittens accounted for. The house has nothing else to hide.'}]}
};
const roomIds=Object.keys(rooms),blank=()=>({room:'foyer',x:29,y:18,visited:['foyer'],met:[],solved:[],items:[],notes:[],steps:0,pets:0,hints:{},seconds:0,won:false,started:false});
let state=blank(),storageOK=true;try{const saved=JSON.parse(localStorage.getItem(SAVE));if(saved&&rooms[saved.room]&&Array.isArray(saved.solved)&&Array.isArray(saved.visited)&&Array.isArray(saved.items)&&Array.isArray(saved.met)){state={...blank(),...saved};state.notes=Array.isArray(state.notes)?state.notes:[];state.hints=state.hints&&typeof state.hints==='object'?state.hints:{};if(!Number.isInteger(state.x)||!Number.isInteger(state.y)||state.x<1||state.x>W-2||state.y<1||state.y>H-2){state.x=29;state.y=20;}}}catch{storageOK=false;}
let panel='play',selected=null,bookType='caesar',path=[],tick=0,sound=false,audio=null;const catPos=Object.fromEntries(cats.map(c=>[c.id,{x:c.x,y:c.y}]));
const doorCoords={n:[29,0],s:[29,H-1],w:[0,11],e:[W-1,11]},opposite={n:'s',s:'n',w:'e',e:'w'};
const names={caesar:'CAESAR SHIFT',atbash:'ATBASH MIRROR',numbers:'A1Z26 NUMBERS',reverse:'REVERSED TEXT',morse:'MORSE TAPS',vigenere:'VIGENERE / CAT'};
function buildRoom(id){const room=rooms[id],grid=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>({ch:x===0||x===W-1||y===0||y===H-1?'#':'.',kind:x===0||x===W-1||y===0||y===H-1?'wall':'floor',solid:x===0||x===W-1||y===0||y===H-1})));function stamp(x,y,lines,solid=true){lines.forEach((line,dy)=>[...line].forEach((ch,dx)=>{if(ch!==' '&&grid[y+dy]?.[x+dx])grid[y+dy][x+dx]={ch,kind:solid?'prop':'carpet',solid};}));}room.props.forEach(p=>stamp(...p));for(const [dir,to]of Object.entries(room.exits)){const[x,y]=doorCoords[dir];grid[y][x]={ch:'+',kind:'door',solid:false,to,dir};let name=to==='vault'?'SEALED DOOR':rooms[to].name.replace('The ','').toUpperCase();if(dir==='n')stamp(29-Math.floor(name.length/2),1,[name],false);if(dir==='s')stamp(29-Math.floor(name.length/2),H-2,[name],false);if(dir==='w')stamp(2,10,[name],false);if(dir==='e')stamp(W-name.length-2,10,[name],false);}for(const clue of room.clues){grid[clue.y][clue.x]={ch:state.items.includes(clue.item)?'.':'?',kind:state.items.includes(clue.item)?'floor':'clue',solid:false,clue};}return grid;}
let grid=buildRoom(state.room);
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));$('save-status').textContent='LOCAL SAVE: SYNCED';}catch{storageOK=false;$('save-status').textContent='SAVE UNAVAILABLE';}}
function tone(hz=330,duration=.07){if(!sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}catch{}}
function log(msg){state.notes.unshift(msg);state.notes=state.notes.slice(0,6);$('notes').textContent=msg;}
function say(speaker,text,code=''){selected=null;$('speaker').textContent='> '+speaker.toUpperCase();$('dialogue').textContent=text;$('encrypted').textContent=code;$('cipher-label').textContent='LISTEN CLOSELY';$('decode-form').hidden=true;$('vault-form').hidden=true;$('feedback').textContent='';}
function render(){const room=rooms[state.room];let html='';for(let y=0;y<H;y++){let last='',run='';function flush(){if(run){html+='<span class="tile-'+last+'">'+run.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')+'</span>';run='';}}for(let x=0;x<W;x++){let cell=grid[y][x],ch=cell.ch,kind=cell.kind;const cat=cats.find(c=>c.room===state.room&&catPos[c.id].x===x&&catPos[c.id].y===y);if(cat){ch=state.solved.includes(cat.id)?cat.glyph.toUpperCase():cat.glyph;kind='cat';}if(x===state.x&&y===state.y){ch='@';kind='you';}if(kind!==last){flush();last=kind;}run+=ch;}flush();if(y<H-1)html+='\n';}$('screen').innerHTML=html;$('screen').setAttribute('aria-label',room.name+'. You are @ at column '+state.x+', row '+state.y+'. '+cats.filter(c=>c.room===state.room).map(c=>c.name+' is '+c.glyph+'.').join(' '));$('room-number').textContent=String(roomIds.indexOf(state.room)+1).padStart(2,'0')+' / '+room.floor;$('room-name').textContent=room.name.toUpperCase();$('room-description').textContent=room.flavor;$('room-weather').textContent=state.room==='cellar'?'A SMALL VOICE BELOW':state.room==='vault'?'NINE KITTENS, SAFE':'RAIN AT THE WINDOWS';$('footsteps').textContent=String(state.steps).padStart(2,'0')+' STEPS';$('progress').textContent=state.solved.length+' / 8 MESSAGES DECODED';$('rooms-count').textContent=state.visited.length+' / 12 ROOMS VISITED';const words=Array(6).fill('____');cats.forEach(c=>{if(c.slot!==undefined&&state.solved.includes(c.id))words[c.slot]=c.word;});$('whisper').textContent='1 '+words[0].padEnd(9)+' 2 '+words[1]+'\n3 '+words[2].padEnd(9)+' 4 '+words[3]+'\n5 '+words[4].padEnd(9)+' 6 '+words[5];$('inventory').textContent='[x] Pocket codebook\n'.replace('\n','');$('inventory').innerHTML='[x] Pocket codebook<br>'+ (state.items.includes('lamp')?'[x] Storm lamp':'[ ] Storm lamp')+'<br>'+(state.items.includes('key')?'[x] Brass key':'[ ] Brass key');$('objective').textContent=state.won?'Button is safe. Stay, explore, and pet the remaining witnesses.':state.solved.filter(id=>cats.find(c=>c.id===id)?.word).length===6?'All six words found. Take your lamp and key to the cellar, then whisper at the sealed door.':'Eight small witnesses. Six hidden words. One door below the house.';if(state.notes.length)$('notes').textContent=state.notes[0];}
function travel(id,fromDir){if(id==='cellar'&&(!state.items.includes('key')||!state.items.includes('lamp'))){say('The cellar gate',!state.items.includes('key')?'The gate is locked. A brass key must be somewhere in the bedrooms.':'You unlock the gate, but the stairs vanish into total darkness. Find a lamp before going down.');tone(130);return false;}if(id==='vault'&&!state.won){vault();return false;}path=[];state.room=id;grid=buildRoom(id);const dir=opposite[fromDir]||'s';const [x,y]=doorCoords[dir];state.x=dir==='w'?1:dir==='e'?W-2:x;state.y=dir==='n'?1:dir==='s'?H-2:y;if(grid[state.y][state.x].solid){state.x=29;state.y=20;}if(!state.visited.includes(id))state.visited.push(id);say(rooms[id].name,rooms[id].flavor);tone(260);save();render();return true;}
function move(dx,dy){if(panel!=='play'||hasDialog())return;const x=state.x+dx,y=state.y+dy,cell=grid[y]?.[x];if(!cell||cell.solid){tone(110,.025);return;}const cat=cats.find(c=>c.room===state.room&&catPos[c.id].x===x&&catPos[c.id].y===y);if(cat){path=[];talk(cat);return;}state.steps++;if(cell.to){travel(cell.to,cell.dir);return;}state.x=x;state.y=y;tone(175+Math.random()*35,.018);save();render();}
function nearby(){const things=[...cats.filter(c=>c.room===state.room).map(c=>({cat:c,x:catPos[c.id].x,y:catPos[c.id].y})),...rooms[state.room].clues.filter(c=>!c.item||!state.items.includes(c.item)).map(c=>({clue:c,x:c.x,y:c.y}))];return things.map(t=>({...t,d:Math.abs(t.x-state.x)+Math.abs(t.y-state.y)})).filter(t=>t.d<=2).sort((a,b)=>a.d-b.d)[0];}
function interact(){path=[];const target=nearby();if(target?.cat)talk(target.cat);else if(target?.clue)inspect(target.clue);else say('The house','Nothing is within reach. Walk beside a kitten or a ? mark, then press E. Doorways marked + open when you step onto them.');}
function talk(cat){path=[];if(!state.met.includes(cat.id))state.met.push(cat.id);selected=cat;$('speaker').textContent='> '+cat.name.toUpperCase()+' / '+cat.glyph;$('dialogue').textContent=state.solved.includes(cat.id)?cat.after:cat.personality+' "'+cat.tell+'"';$('encrypted').textContent=state.solved.includes(cat.id)?cat.plain:cat.encoded;$('cipher-label').textContent=names[cat.type]+(cat.type==='caesar'?' / +'+cat.key:'');$('decode-form').hidden=state.solved.includes(cat.id);$('vault-form').hidden=true;$('translation').value='';$('feedback').textContent='';$('pinned-clue').textContent=cat.name+': '+cat.encoded;bookType=cat.type;save();render();tone(450,.09);}
function inspect(clue){if(clue.id==='stairs'){travel('cellar','n');return;}if(clue.id==='gate'){vault();return;}if(clue.item&&!state.items.includes(clue.item)){state.items.push(clue.item);grid=buildRoom(state.room);log('Found the '+(clue.item==='key'?'brass cellar key':'storm lamp')+'.');tone(620,.16);}say(clue.name,clue.text);save();render();}
function vault(){say('The whispering door','A sleepy voice asks for six words, in their proper order. Consult your journal and whisper the sentence.');$('vault-form').hidden=false;$('cipher-label').textContent='SIX WORDS / ONE SECRET';}
function normalize(str){return str.toUpperCase().replace(/[^A-Z0-9]/g,'');}
$('decode-form').addEventListener('submit',e=>{e.preventDefault();if(!selected)return;const cat=selected,answer=normalize($('translation').value);if([cat.plain,cat.word,cat.answer].filter(Boolean).some(a=>normalize(a)===answer)){if(!state.solved.includes(cat.id))state.solved.push(cat.id);log(cat.name+' decoded'+(cat.word?': word '+(cat.slot+1)+' is '+cat.word+'.':'.'));$('dialogue').textContent=cat.after;$('encrypted').textContent=cat.plain;$('decode-form').hidden=true;$('feedback').textContent=cat.word?'[OK] Word '+(cat.slot+1)+' added to your whisper.':'[OK] Message recorded in your journal.';tone(740,.18);save();render();}else{$('feedback').textContent='[?] Not quite. Check the codebook, or ask for a hint. There is no penalty.';tone(180);}});
$('vault-form').addEventListener('submit',e=>{e.preventDefault();if(normalize($('password').value)===normalize('WHEN THE MOON SLEEPS WE PURR')){state.won=true;log('Found Button. All nine kittens are safe.');travel('vault','n');$('ending-stats').textContent=state.solved.length+'/8 messages decoded. '+state.pets+' pets given. '+Object.values(state.hints).reduce((a,b)=>a+b,0)+' hints used.';$('ending').showModal();save();tone(880,.35);}else $('feedback').textContent='The door stays quiet. Six words, in numbered order. Perhaps a kitten knows the missing word.';});
function hint(){if(!selected||state.solved.includes(selected.id))return;const n=state.hints[selected.id]||0;state.hints[selected.id]=Math.min(3,n+1);const hints=[names[selected.type]+'. '+selected.tell,'The message begins: '+selected.plain.split(' ').slice(0,3).join(' ')+'. Check the codebook example.','The full translation is: '+selected.plain+'. Enter it to record the clue.'];$('feedback').textContent='[HINT '+Math.min(3,n+1)+'/3] '+hints[Math.min(2,n)];save();}
function pet(){const near=cats.filter(c=>c.room===state.room).find(c=>Math.abs(catPos[c.id].x-state.x)+Math.abs(catPos[c.id].y-state.y)<=2);if(!near){say('The house','Your hand is ready. Your kitten is elsewhere. Walk closer to one.');return;}state.pets++;say(near.name,near.pet);log('Petted '+near.name+'. An excellent use of your time.');save();render();tone(220,.25);}
function hasDialog(){return !!document.querySelector('dialog[open]');}
function setPanel(name){panel=name;path=[];for(const n of ['play','book','journal','atlas'])$(n+'-panel').hidden=n!==name;document.querySelectorAll('nav [data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));if(name==='book')renderBook();if(name==='journal')renderJournal();if(name==='atlas')renderAtlas();}
const bookPages={
caesar:{title:'01 / The alphabet takes a walk',body:'A Caesar cipher moves every letter forward by the same number. To read it, move BACK by that number. Pip uses +3; Ash uses +5. Keep spaces as they are.',diagram:'PLAIN   ABCDEFGHIJKLMNOPQRSTUVWXYZ\nPIP +3  DEFGHIJKLMNOPQRSTUVWXYZABC\nASH +5  FGHIJKLMNOPQRSTUVWXYZABCDE\n\nEXAMPLE (+3):  FDW -> CAT\n               F back 3 = C\n               D back 3 = A\n               W back 3 = T',tip:'Find an encoded letter on the shifted line. Read the plain letter directly above it.'},
atbash:{title:'02 / A mirror for your alphabet',body:'The first letter becomes the last. The second becomes the second-last. The same rule encodes and decodes. Ink and Velvet speak this way.',diagram:'PLAIN   ABCDEFGHIJKLMNOPQRSTUVWXYZ\nMIRROR  ZYXWVUTSRQPONMLKJIHGFEDCBA\n\nEXAMPLE:  XZG -> CAT\n          X = C, Z = A, G = T',tip:'Use either line to find the kitten\'s letter. Read its partner on the other line.'},
numbers:{title:'03 / Twenty-six tiny numbers',body:'A is 1. B is 2. Continue to Z, which is 26. Hyphens separate letters; a slash separates words. Biscuit would prefer to count snacks.',diagram:' A  B  C  D  E  F  G  H  I  J  K  L  M\n01 02 03 04 05 06 07 08 09 10 11 12 13\n\n N  O  P  Q  R  S  T  U  V  W  X  Y  Z\n14 15 16 17 18 19 20 21 22 23 24 25 26\n\nEXAMPLE:  3-1-20 / 14-1-16 -> CAT NAP',tip:'Read one number at a time. The slash / starts a new word.'},
reverse:{title:'04 / Begin at the other end',body:'Fern reverses the entire message, including the order of its words. Start at the very last character and read toward the first.',diagram:'EXAMPLE:  SPAN TAC EHT\n\nRead right to left:\n          THE CAT NAPS',tip:'Write the letters from the end to the beginning. Spaces remain spaces.'},
morse:{title:'05 / Short taps. Long taps.',body:'A dot is a short tap. A dash is a long tap. Each group is one letter. Spaces separate letters, and / separates words. Echo taps instead of talking.',diagram:'A .-     B -...   C -.-.   D -..\nE .      F ..-.   G --.    H ....\nI ..     J .---   K -.-    L .-..\nM --     N -.     O ---    P .--.\nQ --.-   R .-.    S ...    T -\nU ..-    V ...-   W .--    X -..-\nY -.--   Z --..\n\nEXAMPLE:  -.-. .- - -> CAT',tip:'Match whole groups. A dot on its own means E; it is not the beginning of the next group.'},
vigenere:{title:'06 / A repeating little key',body:'Moth uses the key CAT. Unlike the numbered alphabet, here A=0 and Z=25. Repeat CAT beneath the message. Subtract each key letter\'s number from the message letter. If the result is negative, add 26. Do not advance the key for spaces.',diagram:'LETTER  ABCDEFGHIJKLMNOPQRSTUVWXYZ\nVALUE   0 1 2 3 4 5 6 7 8 9 ... 25\nKEY     C=2    A=0    T=19\n\nEXAMPLE:\nMESSAGE EAM\nKEY     CAT\n        4-2 = 2  -> C\n        0-0 = 0  -> A\n       12-19=-7; +26=19 -> T\n\nEAM -> CAT',tip:'Every third letter uses T (subtract 19). Only letters count; skip spaces.'}
};
function renderBook(){const tabs=$('book-tabs');tabs.replaceChildren();Object.keys(bookPages).forEach(type=>{const b=document.createElement('button');b.textContent='['+names[type].split(' ')[0]+']';b.classList.toggle('active',type===bookType);b.onclick=()=>{bookType=type;renderBook();};tabs.append(b);});const page=bookPages[bookType];$('book-page').replaceChildren();for(const [tag,text,cls]of [['h3',page.title],['p',page.body],['pre',page.diagram,'diagram'],['p','TIP > '+page.tip,'muted']]){const el=document.createElement(tag);el.textContent=text;if(cls)el.className=cls;$('book-page').append(el);}}
function renderJournal(){const root=$('journal-entries');root.replaceChildren();if(!state.met.length){const p=document.createElement('p');p.textContent='No messages yet. Pip is waiting in the foyer. Walk beside the letter a and press E.';root.append(p);}cats.filter(c=>state.met.includes(c.id)).forEach(c=>{const el=document.createElement('div');el.className='entry';const head=document.createElement('h3');head.textContent=(state.solved.includes(c.id)?'[DECODED] ':'[UNSOLVED] ')+c.name+' / '+rooms[c.room].name;const text=document.createElement('pre');text.textContent=c.encoded;el.append(head,text);if(state.solved.includes(c.id)){const plain=document.createElement('p');plain.className='decoded';plain.textContent='> '+c.plain;el.append(plain);}else{const b=document.createElement('button');b.textContent='[WORK ON THIS MESSAGE]';b.onclick=()=>{setPanel('play');talk(c);};el.append(b);}root.append(el);});const p=document.createElement('p');p.textContent='Pets given: '+state.pets+'. This is the only statistic that truly matters.';root.append(p);}
function renderAtlas(){$('atlas-art').textContent='                  [ ATTIC ]\n                      |\n [ MUSIC ] ---- [ GALLERY ] ---- [ BEDROOM ]\n                      |\n                      |\n                      |\n [CONSERVATORY]        |         [ KITCHEN ]\n       |              |              |\n [ LIBRARY ] ------ [ HALL ] ----- [ DINING ]\n                      |\n                  [ FOYER ]\n\n GALLERY stairs -> CELLAR -> SECRET NURSERY';const root=$('room-directory');root.replaceChildren();roomIds.forEach((id,i)=>{const b=document.createElement('button');const seen=state.visited.includes(id);b.textContent='['+String(i+1).padStart(2,'0')+'] '+(seen?rooms[id].name:'??? / '+rooms[id].floor);b.disabled=!seen;b.onclick=()=>{setPanel('play');path=[];state.room=id;state.x=29;state.y=20;grid=buildRoom(id);say(rooms[id].name,'You return along a familiar route. '+rooms[id].flavor);save();render();};root.append(b);});}
function findPath(tx,ty,adjacent=false){const start=[state.x,state.y],queue=[start],seen=new Set([start.join(',')]),prev=new Map();let end=null;for(let n=0;n<queue.length;n++){const[x,y]=queue[n];if(adjacent?Math.abs(x-tx)+Math.abs(y-ty)<=1:x===tx&&y===ty){end=[x,y];break;}for(const[dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){const nx=x+dx,ny=y+dy,key=nx+','+ny,cell=grid[ny]?.[nx];if(!cell||cell.solid||seen.has(key))continue;if(cell.to&&!(nx===tx&&ny===ty))continue;if(cats.some(c=>c.room===state.room&&catPos[c.id].x===nx&&catPos[c.id].y===ny))continue;seen.add(key);prev.set(key,[x,y]);queue.push([nx,ny]);}}if(!end)return null;const out=[];while(end[0]!==start[0]||end[1]!==start[1]){out.unshift(end);end=prev.get(end.join(','));}return out;}
let onArrival=null;
$('screen').onclick=e=>{if(panel!=='play'||hasDialog())return;const rect=$('screen').getBoundingClientRect(),size=parseFloat(getComputedStyle($('screen')).fontSize),line=parseFloat(getComputedStyle($('screen')).lineHeight);const probe=document.createElement('canvas').getContext('2d');probe.font=size+'px "Courier New", Courier, monospace';const cw=probe.measureText('M').width;const x=Math.floor((e.clientX-rect.left)/cw),y=Math.floor((e.clientY-rect.top)/line);if(x<0||x>=W||y<0||y>=H)return;const cat=cats.find(c=>c.room===state.room&&catPos[c.id].x===x&&catPos[c.id].y===y),clue=grid[y][x].clue;const route=findPath(x,y,!!(cat||clue));if(!route){$('feedback').textContent='That spot is out of reach. Try a clear floor tile.';return;}path=route;onArrival=cat?()=>talk(cat):clue?()=>inspect(clue):null;if(!path.length&&onArrival){onArrival();onArrival=null;}};
document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{path=[];onArrival=null;move(...b.dataset.move.split(',').map(Number));});document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>setPanel(b.dataset.panel));$('interact').onclick=interact;$('pet').onclick=pet;$('hint').onclick=hint;
$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();$('restart').onclick=()=>$('confirm-dialog').showModal();$('cancel-restart').onclick=()=>$('confirm-dialog').close();$('confirm-restart').onclick=()=>{state=blank();path=[];onArrival=null;cats.forEach(c=>catPos[c.id]={x:c.x,y:c.y});grid=buildRoom('foyer');$('confirm-dialog').close();setPanel('play');say('The house','A new night. A fresh set of pawprints. Pip waits in the foyer.');save();render();$('intro').showModal();};$('sound').onclick=()=>{sound=!sound;$('sound').textContent='[SOUND: '+(sound?'ON':'OFF')+']';if(sound)tone(330,.15);};
function start(){state.started=true;$('intro').close();save();$('screen').focus({preventScroll:true});}$('start').onclick=start;$('keep-playing').onclick=()=>$('ending').close();$('intro').addEventListener('cancel',e=>{e.preventDefault();start();});
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select')){if(e.key==='Escape'){e.target.blur();setPanel('play');}return;}if(hasDialog()){if(e.key==='Enter'&&$('intro').open){e.preventDefault();start();}else if(e.key==='Enter'&&$('ending').open)$('ending').close();return;}const k=e.key.toLowerCase();const keys={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0]};if(keys[k]){e.preventDefault();path=[];onArrival=null;move(...keys[k]);}else if(k==='e'||k===' '){e.preventDefault();if(panel==='play')interact();}else if(k==='p'&&panel==='play')pet();else if(k==='h'&&panel==='play')hint();else if(['1','2','3','4'].includes(k)){e.preventDefault();setPanel(['play','book','journal','atlas'][+k-1]);}else if(k==='escape')setPanel('play');else if(k==='?')$('help-dialog').showModal();});
setInterval(()=>{if(!state.started||hasDialog()||panel!=='play')return;tick++;if(path.length){const[nextX,nextY]=path.shift();const dx=nextX-state.x,dy=nextY-state.y;if(Math.abs(dx)+Math.abs(dy)===1)move(dx,dy);else{path=[];onArrival=null;}if(!path.length&&onArrival){const done=onArrival;onArrival=null;done();}}if(tick%16===0&&!path.length){cats.filter(c=>c.room===state.room&&selected?.id!==c.id).forEach(c=>{if(Math.random()>.5)return;const pos=catPos[c.id],[dx,dy]=[[0,-1],[1,0],[0,1],[-1,0]][Math.floor(Math.random()*4)],x=pos.x+dx,y=pos.y+dy;const cell=grid[y]?.[x];if(cell&&!cell.solid&&!cell.to&&!cell.clue&&Math.abs(x-c.x)<=3&&Math.abs(y-c.y)<=2&&Math.abs(x-state.x)+Math.abs(y-state.y)>2&&!cats.some(other=>other.room===c.room&&catPos[other.id].x===x&&catPos[other.id].y===y)){pos.x=x;pos.y=y;}});render();}},100);
setInterval(()=>{if(state.started&&!hasDialog()){state.seconds++;$('clock').textContent=String(Math.floor(state.seconds/60)).padStart(2,'0')+':'+String(state.seconds%60).padStart(2,'0');if(state.seconds%10===0)save();}},1000);
window.addEventListener('pagehide',save);render();if(!storageOK)$('save-status').textContent='SAVE UNAVAILABLE';if(!state.started)$('intro').showModal();else say(rooms[state.room].name,'Welcome back. The house kept your place. '+rooms[state.room].flavor);
})();
