'use strict';
(() => {
const $=id=>document.getElementById(id),D=window.AsciAdventure,rooms=D.rooms,cats=D.cats,W=58,H=23,SAVE='ascicat.adventure.v2',Player=window.BramblePlayer;
const verbs=['walk','look','use','push','pull','open','close','talk','take','pet'];
const items={crank:{name:'Brass crank',look:'A small crank with a square shaft. It fits the socket on the cellar crate.'},oil:{name:'Lamp oil',look:'A sealed tin of clean lamp oil.'},lamp:{name:'Storm lamp',look:'A storm lamp with a dry reservoir.'},matches:{name:'Matches',look:'A box of dry matches. Enough for several attempts.'},key:{name:'Cellar key',look:'A tiny brass key shaped like a sleeping kitten.'},hook:{name:'Long brass hook',look:'A long hook from the conservatory ledge. It could reach a latch.'},weight:{name:'Brass weight',look:'A heavy counterweight with a ring for a hanging chain.'},ribbon:{name:'Blue ribbon',look:'A spare blue ribbon. Button would probably like it.'}};
const fresh=()=>({playerStyle:Player.randomStyle(),room:'foyer',x:29,y:20,visited:['foyer'],items:[],taken:[],flags:{},orientations:[3,2,1],melody:[],crate:0,notes:[],met:[],pets:0,steps:0,seconds:0,won:false,started:false});
let state=fresh();try{const p=JSON.parse(localStorage.getItem(SAVE));if(p&&rooms[p.room]&&Array.isArray(p.items)&&Array.isArray(p.visited)&&p.flags&&Array.isArray(p.orientations)){state={...fresh(),...p};state.items=state.items.filter(i=>items[i]);state.orientations=state.orientations.map(n=>Number.isInteger(n)?((n%4)+4)%4:0).slice(0,3);while(state.orientations.length<3)state.orientations.push(0);state.crate=Math.max(0,Math.min(3,state.crate||0));}}catch{}
if(!Player.isStyle(state.playerStyle))state.playerStyle=Player.randomStyle();
let panel='play',verb='look',held=null,hover=null,lastTarget=null,route=[],arrival=null,pendingMove=null,grid,scene=[],seconds=0;
const reducedMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)');
const playerMotion=Player.create(state.room,state.x,state.y,{enabled:typeof requestAnimationFrame==='function',reduced:!!reducedMotion?.matches});
const audio=new window.AsciCatAudio(),pos=Object.fromEntries(cats.map(c=>[c.id,{x:c.x,y:c.y}])),doors={n:[29,0],s:[29,22],w:[0,11],e:[57,11]},opposite={n:'s',s:'n',w:'e',e:'w'};
const milestones=[['portraitLifted','Found the portrait sketch'],['bookcaseMoved','Revealed the hidden recess'],['lampLit','Lit the storm lamp'],['portraitsAligned','Aligned the gallery portraits'],['hookReached','Reached the high ledge'],['melodySolved','Opened the piano drawer'],['cellarUnlocked','Unlocked the cellar'],['crateOnPlate','Set the pressure plate'],['chainBalanced','Balanced the chain'],['latchReleased','Released the high latch']];
function save(){try{localStorage.setItem(SAVE,JSON.stringify(state));$('save-status').textContent='Progress saved';}catch{$('save-status').textContent='Saving unavailable';}}
function note(text){if(!state.notes.includes(text)){state.notes.unshift(text);state.notes=state.notes.slice(0,80);}save();}
function flag(id,text){if(!state.flags[id]){state.flags[id]=true;note(text);audio.play('solve');}render();}
function say(speaker,text,cat=null){$('speaker').textContent=speaker;$('dialogue').textContent=text;$('feedback').textContent='';$('interaction-label').textContent=cat?'KITTEN CONVERSATION':'FIELD OBSERVATION';audio.stopEffects();if(cat)audio.catDialogue(text,cat.id);else audio.speak(text);}
function feedback(text){$('feedback').textContent=text;}
function hasDialog(){return !!document.querySelector('dialog[open]');}
function isOpen(id){return !!state.flags['open:'+id];}
function itemObject(id,room,x,y){return {id:'item:'+id,item:id,name:items[id].name,room,x,y,art:['■'],look:items[id].look,walkable:true};}
function objectsFor(id){let list=D.objects.filter(o=>o.room===id).map(o=>({...o,art:o.art.slice()}));for(const o of list){if(o.id==='bookcase'&&state.flags.bookcaseMoved)o.x+=12;if(o.id==='bench'&&state.flags.benchMoved)o.x=27;if(o.id==='crate')o.x+=state.crate*5;if(o.rotation){const i=['west','center','east'].indexOf(o.rotation);o.art[3]='█     '+['^','>','v','<'][state.orientations[i]]+'     █';}if(o.id==='familyPortrait'&&state.flags.portraitLifted)o.art=['█▀▀▀▀▀▀▀▀▀▀▀▀█','█  SKETCH    █','█  >  ^  <   █','█▄▄▄▄▄▄▄▄▄▄▄▄█'];if(o.id==='plate'&&state.flags.crateOnPlate)o.art=['▄▄▄▄▄▄'];if(o.curtain&&isOpen(o.id))o.art=['▓░░░░░░▓','▓░RAIN░▓','▓░░░░░░▓','▓░░░░░░▓'];else if(isOpen(o.id)&&o.openable)o.art=o.art.map((r,i)=>i===1?r.replace(/■/g,'░'):r);}
 const reveal=(item,room,x,y,condition)=>{if(id===room&&condition&&!state.taken.includes(item))list.push(itemObject(item,room,x,y));};
 reveal('crank','foyer',45,9,state.flags.portraitLifted);reveal('oil','library',9,6,state.flags.bookcaseMoved);reveal('lamp','kitchen',43,9,isOpen('cupboard'));reveal('matches','dining',46,19,isOpen('sideboard'));reveal('key','gallery',29,10,state.flags.portraitsAligned);reveal('hook','conservatory',31,14,state.flags.hookReached);reveal('weight','music',15,13,isOpen('piano')&&state.flags.melodySolved);reveal('ribbon','bedroom',18,19,state.flags.rugLifted);
 for(const [dir,to]of Object.entries(rooms[id].exits)){const[x,y]=doors[dir];list.push({id:'door:'+dir,name:rooms[to].name,room:id,x,y,art:['+'],walkable:true,to,dir,look:'A doorway leading to '+rooms[to].name+'.'});}
 return list;
}
function build(){scene=objectsFor(state.room);grid=Array.from({length:H},(_,y)=>Array.from({length:W},(_,x)=>({ch:x===0||x===57||y===0||y===22?'█':' ',kind:x===0||x===57||y===0||y===22?'wall':'floor',solid:x===0||x===57||y===0||y===22})));
 // Floor patterns and rails stay below furniture and items.
 if(state.room==='hall')for(let y=7;y<=16;y++)for(let x=20;x<=37;x++)grid[y][x]={ch:'░',kind:'carpet',solid:false};
 if(state.room==='cellar')for(let x=23;x<=45;x++)grid[18][x]={ch:'░',kind:'carpet',solid:false};
 const sorted=[...scene].sort((a,b)=>Number(!!b.walkable)-Number(!!a.walkable));
 for(const o of sorted){o.art.forEach((line,dy)=>[...line].forEach((ch,dx)=>{const x=o.x+dx,y=o.y+dy;if(ch!==' '&&grid[y]?.[x])grid[y][x]={ch,kind:o.item?'clue':o.to?'door':o.walkable?'carpet':'prop',solid:!o.walkable,object:o};}));}
 // A key is playable even though it is inset in the piano's cabinet.
 for(const o of scene.filter(o=>o.key))o.art[0].split('').forEach((ch,dx)=>{grid[o.y][o.x+dx]={ch,kind:'clue',solid:true,object:o};});
 for(const [dir,to]of Object.entries(rooms[state.room].exits)){const[x,y]=doors[dir];grid[y][x]={ch:'+',kind:'door',solid:false,object:scene.find(o=>o.id==='door:'+dir)};if(dir==='n'||dir==='s'){const label=rooms[to].name.replace(/^The /,'').toUpperCase(),row=dir==='n'?1:21;[...label].forEach((ch,i)=>{grid[row][29-Math.floor(label.length/2)+i]={ch,kind:'label',solid:false};});}}
}
function render(){build();if(grid[state.y]?.[state.x]?.solid){state.x=29;state.y=20;}playerMotion.sync(state.room,state.x,state.y);const room=rooms[state.room],focused=document.activeElement?.closest?.('[data-target]')?.getAttribute('data-target');$('screen').innerHTML=window.BrambleVisuals.render({state,scene,cats,pos,room,player:playerMotion});if(focused)$('screen').querySelector('[data-target="'+focused+'"]')?.focus({preventScroll:true});$('screen').setAttribute('aria-label',room.name+'. Interactive room. Choose an action, then click furniture, a kitten, or a doorway.');$('room-name').textContent=room.name;$('room-number').textContent=String(Object.keys(rooms).indexOf(state.room)+1).padStart(2,'0')+' / '+room.floor;$('room-description').textContent=room.flavor;$('room-weather').textContent=state.room==='cellar'?'MECHANISMS BELOW':state.won?'NINE KITTENS, SAFE':'RAIN AT THE WINDOWS';$('footsteps').textContent=state.steps+' steps';$('progress').textContent=milestones.filter(([f])=>state.flags[f]).length+' / '+milestones.length+' discoveries';$('rooms-count').textContent=state.visited.length+' / 12 rooms';$('notes').textContent=state.notes[0]||'Inspect a portrait. Open a cupboard. Trust the paws.';$('objective').textContent=state.won?'Button is safe. You may now pet absolutely everyone.':!state.flags.cellarUnlocked?'Search the house for a cellar key and a working lamp. The portraits, piano, and furniture hold the clues.':'The nursery has three catches: a pressure plate, a balanced chain, and a high latch.';$('mechanisms').textContent=(state.flags.crateOnPlate?'✓':'○')+'  Floor plate\n'+(state.flags.chainBalanced?'✓':'○')+'  Balanced chain\n'+(state.flags.latchReleased?'✓':'○')+'  High latch';$('clock').textContent=String(Math.floor(state.seconds/60)).padStart(2,'0')+':'+String(state.seconds%60).padStart(2,'0');renderPockets();renderRoomObjects();updateVerb();}
function renderPockets(){const root=$('inventory');root.replaceChildren();if(!state.items.length){const p=document.createElement('p');p.textContent='A promising amount of pocket space.';root.append(p);}for(const id of state.items){const b=document.createElement('button');b.className='inventory-item'+(held===id?' selected':'');b.innerHTML=window.BrambleVisuals.icon(id);const label=document.createElement('span');label.textContent=id==='lamp'&&state.flags.lampLit?'Lit storm lamp':items[id].name;b.append(label);b.setAttribute('aria-pressed',String(held===id));b.onclick=()=>inventoryClick(id);root.append(b);}}
function updateVerb(){document.querySelectorAll('[data-verb]').forEach(b=>{b.classList.toggle('active',b.dataset.verb===verb);b.setAttribute('aria-pressed',String(b.dataset.verb===verb));});$('action-line').textContent=({look:'Look at',talk:'Talk to'}[verb]||verb[0].toUpperCase()+verb.slice(1))+(held?' '+items[held].name.toLowerCase()+' with':'')+(hover?' '+hover.name.toLowerCase():held?' something in the room':' something in the room');}
function selectVerb(v){verb=v;if(v!=='use')held=null;route=[];arrival=null;pendingMove=null;updateVerb();}
function inventoryClick(id){if(verb==='look'){say(items[id].name,id==='lamp'?(state.flags.lampLit?'The storm lamp burns steadily.':state.flags.lampFilled?'A filled storm lamp. It still needs a flame.':items[id].look):items[id].look);return;}if(verb==='use'&&held&&held!==id){useItem(held,{id:'inventory:'+id,item:id,name:items[id].name});return;}held=held===id?null:id;verb='use';updateVerb();renderPockets();}
function acquire(id){if(state.taken.includes(id))return;state.taken.push(id);state.items.push(id);note('Found '+items[id].name+'.');say(items[id].name,'You take '+items[id].name.toLowerCase()+'.');audio.play('pickup');render();save();}
function catLines(cat){const hints={pip:state.flags.portraitLifted?'The three portrait kittens upstairs should face right, up, and left. I posed for the middle one. I was very brave.':'That family portrait lifts from the bottom. Humans never pull things gently enough.',ink:state.flags.bookcaseMoved?'Oil behind a bookcase. A little irresponsible, but wonderfully secret.':'My favourite bookcase has wheels. Push it to the right. Mind my tail.',biscuit:'I put the matches in the sideboard drawer. The lamp is in the kitchen cupboard. The oil? Ask Ink.',fern:state.flags.benchMoved?'Use the bench to climb up to the ledge. There is a splendid long hook up there.':'The high window ledge is too tall. Push the bench underneath it, then use the bench.',echo:state.flags.melodySolved?'The piano drawer is openable now. Something heavy lives inside.':'Look at the pianist portrait. Moon, eye, whisker. Use those keys in that order. I composed it myself.',moth:'The nursery has three catches. Crate on the floor plate. Weight on the chain. Hook on the latch. I am extremely good at supervising.',ash:state.flags.cellarUnlocked?'You may pass. The cellar is an officially sanctioned place for naps.':'Velvet guards the three turning portraits. A family sketch explains how to face them.',velvet:state.flags.portraitsAligned?'The centre frame has dropped a brass key. Do take it before Biscuit decides it is cutlery.':'Push a portrait to turn it clockwise. Pull turns it back. The family sketch downstairs shows how they should face.',button:'Mrrp. I was only having a nap. Can you tell everyone to keep it down?'};return hints[cat.id];}
function talk(cat){if(!state.met.includes(cat.id))state.met.push(cat.id);lastTarget=cat;say(cat.name,catLines(cat),cat);note(cat.name+': '+catLines(cat));save();render();}
function pet(cat){state.pets++;lastTarget=cat;say(cat.name,cat.pet,cat);audio.play('purr');save();render();}
function rotate(o,delta){const i=['west','center','east'].indexOf(o.rotation);state.orientations[i]=(state.orientations[i]+delta+4)%4;say(o.name,'You turn the portrait. It now faces '+['up','right','down','left'][state.orientations[i]]+'.');audio.play('door');if(state.orientations.join(',')==='1,0,3')flag('portraitsAligned','The portraits face right, up, and left. The centre frame drops a brass cellar key.');render();save();}
function useItem(item,o){const target=o.item||o.id;
 if((item==='oil'&&target==='lamp')||(item==='lamp'&&target==='oil')){state.flags.lampFilled=true;say('Storm lamp','You fill the reservoir with oil. Now it needs a flame.');note('Filled the storm lamp with oil.');}
 else if((item==='matches'&&target==='lamp')||(item==='lamp'&&target==='matches')||(item==='lamp'&&target==='stove')){if(!state.flags.lampFilled)say('Storm lamp','The lamp is dry. Fill it with oil first.');else{flag('lampLit','The storm lamp is lit. The cellar will be safe to explore.');say('Storm lamp','The wick catches. A small amber flame fills the room.');audio.play('pickup');}}
 else if(item==='key'&&target==='stairs'){flag('cellarUnlocked','Unlocked the cellar gate with the portrait key.');say('Cellar gate','The brass key turns neatly. The stairs are unlocked. Open the gate when your lamp is lit.');audio.play('door');}
 else if(item==='crank'&&target==='crate'){flag('crateReleased','Fitted the crank to the crate. Push moves it right; pull moves it left.');say('Rolling crate','The crank releases the wheels. PUSH slides the crate right along the rail. PULL brings it left.');}
 else if(item==='weight'&&target==='chain'){flag('chainBalanced','The brass weight balances the hanging chain.');say('Counterbalance','You hang the brass weight from the chain. The middle catch lifts.');}
 else if(item==='hook'&&target==='highLatch'){if(!state.flags.crateOnPlate||!state.flags.chainBalanced)say('High latch','The hook reaches, but the linkage is under tension. Set the floor plate and balance the chain first.');else{flag('latchReleased','Used the brass hook to release the high latch. The nursery door can open.');say('High latch','The hook catches the ring. You pull. The last catch lifts with a quiet click.');audio.play('door');}}
 else if(item==='ribbon'&&(o.id==='button'||o.id==='nest'))say('Button','Button curls around the blue ribbon. It is officially the best ribbon.');
 else say(o.name,'You consider using '+items[item].name.toLowerCase()+' with '+o.name.toLowerCase()+'. Nothing useful happens. Try a different object, or LOOK more closely.');
 held=null;render();save();}
function act(o,v=verb){if(!o)return;lastTarget=o;hover=o;updateVerb();route=[];arrival=null;pendingMove=null;
 if(v==='use'&&held){useItem(held,o);return;}
 if(o.cat){const cat=cats.find(c=>c.id===o.id);if(v==='talk'||v==='use')talk(cat);else if(v==='pet')pet(cat);else if(v==='look')say(cat.name,cat.name+' is an extremely suspicious, extremely soft kitten. Talking may help.');else say(cat.name,v==='take'?'You cannot put a kitten in your pocket. This has been tried.':cat.name+' politely declines being '+({push:'pushed',pull:'pulled',open:'opened',close:'closed'}[v]||v)+'.');return;}
 if(o.item){if(v==='take'||v==='use')acquire(o.item);else if(v==='look')say(o.name,o.look);else say(o.name,'It is small enough to TAKE.');return;}
 if(o.to){if(v==='look')say(o.name,o.look);else if(['walk','open','use'].includes(v))travel(o.to,o.dir);else say(o.name,'This doorway leads to '+o.name+'. OPEN it or WALK through.');return;}
 if(v==='look'){let text=o.look;if(o.rotation)text='A hinged portrait facing '+['up','right','down','left'][state.orientations[['west','center','east'].indexOf(o.rotation)]]+'. Push turns clockwise; pull turns counterclockwise.';if(o.id==='familyPortrait'&&state.flags.portraitLifted)text='The sketch behind the frame shows the gallery portraits: WEST faces RIGHT, CENTRE faces UP, EAST faces LEFT.';if(o.id==='bench'&&state.flags.benchMoved)text='The bench is directly beneath the high window. USE it to reach the ledge.';if(o.id==='crate')text=state.flags.crateReleased?'A rolling crate. PUSH slides it right; PULL slides it left. The plate is at the right-hand end.':o.look;if(o.id==='piano'&&state.flags.melodySolved)text='The melody unlocked the little piano drawer. OPEN the piano to inspect it.';if(o.id==='stairs'&&state.flags.cellarUnlocked)text='The gate is unlocked. Bring a lit storm lamp before going downstairs.';if(isOpen(o.id)&&o.inside)text+=' '+o.inside;say(o.name,text);note(o.name+': '+text);return;}
 if(o.rotation&&(v==='push'||v==='pull')){rotate(o,v==='push'?1:-1);return;}
 if(o.id==='familyPortrait'&&['pull','open','push'].includes(v)){flag('portraitLifted','Behind the family portrait: WEST faces RIGHT, CENTRE faces UP, EAST faces LEFT. A brass crank lies in the recess.');say(o.name,'You lift the frame. Behind it: a sketch of three portraits pointing RIGHT, UP, LEFT, and a small brass crank.');return;}
 if(o.id==='bookcase'&&(v==='push'||v==='pull')){if(v==='push')flag('bookcaseMoved','Pushed the wheeled bookcase aside. A tin of lamp oil is hidden behind it.');else state.flags.bookcaseMoved=false;say(o.name,v==='push'?'The bookcase slides right. A hidden recess holds a tin of lamp oil.':'The bookcase slides back over the recess.');audio.play('door');render();save();return;}
 if(o.id==='bench'&&(v==='push'||v==='pull')){state.flags.benchMoved=v==='push';say(o.name,v==='push'?'You slide the bench beneath the high window. USE it to climb up.':'You pull the bench back beside the plants.');audio.play('door');render();save();return;}
 if(o.id==='bench'&&v==='use'){if(!state.flags.benchMoved)say(o.name,'You climb the bench, but the high ledge is still out of reach. Slide it beneath the window.');else{flag('hookReached','Moved the bench beneath the high window and reached the long brass hook.');say('High window','Standing on the bench, you reach the hook and lay it at your feet. TAKE it.');}return;}
 if(o.id==='highWindow'&&(v==='take'||v==='open'||v==='use')){say(o.name,'The ledge is too high. Move the bench underneath the window and USE the bench.');return;}
 if(o.id==='crate'&&(v==='push'||v==='pull')){if(!state.flags.crateReleased){say(o.name,'The wheels are locked. A square socket needs a crank.');return;}const next=Math.max(0,Math.min(3,state.crate+(v==='push'?1:-1)));if(next===state.crate){say(o.name,'The crate has reached the end of its rail.');return;}state.crate=next;state.flags.crateOnPlate=next===3;if(next===3)note('The crate now holds down the pressure plate.');say(o.name,next===3?'The crate settles on the plate. The first catch lifts.':'The crate rolls '+(v==='push'?'right':'left')+' along the rail.');audio.play('door');render();save();return;}
 if(o.key&&v==='use'){state.melody.push(o.key);const sequence=['moon','eye','whisker'];if(state.melody.every((k,i)=>k===sequence[i])){audio.oscillator({moon:523.25,eye:659.25,whisker:783.99}[o.key],.5,.07);if(state.melody.length===3){flag('melodySolved','Played MOON, EYE, WHISKER. The piano drawer clicks open.');say('Grand piano','Moon, eye, whisker. The melody rings true. A hidden drawer unlocks. OPEN the piano.');state.melody=[];}else say(o.name,'A clear note rings out. The piano is listening.');}else{state.melody=[];say('Grand piano','That sequence does not fit. The keys settle. Look at the pianist portrait for the order.');audio.play('error');}save();render();return;}
 if(o.id==='piano'&&v==='open'){if(!state.flags.melodySolved){say(o.name,'The drawer is locked. Three picture keys might release it.');return;}state.flags['open:piano']=true;say(o.name,'You open the shallow drawer. A brass counterweight rolls into view beneath the keys. TAKE it.');render();save();return;}
 if(o.id==='stairs'&&(v==='open'||v==='use'||v==='walk')){travel('cellar','n');return;}
 if(o.id==='nurseryDoor'&&(v==='open'||v==='use')){if(state.flags.crateOnPlate&&state.flags.chainBalanced&&state.flags.latchReleased){finish();}else say(o.name,'The catches still hold. '+(!state.flags.crateOnPlate?'The floor plate is not pressed. ': '')+(!state.flags.chainBalanced?'The chain is not balanced. ':'')+(!state.flags.latchReleased?'The high latch is not released.':''));return;}
 if((o.id==='welcomeMat'||o.id==='rug')&&(v==='pull'||v==='open')){if(o.id==='rug'){state.flags.rugLifted=true;say(o.name,'You lift the rug corner. A blue ribbon lies beneath it.');}else say(o.name,'You lift the mat. A bent teaspoon stares back. It is decorative rather than useful.');render();save();return;}
 if(o.id==='fernPot'&&(v==='push'||v==='pull')){say(o.name,'Under the pot: a sketch of a bench beneath the high window. Fern was planning something.');note('Garden sketch: move the bench under the high window.');return;}
 if(o.curtain&&(v==='pull'||v==='open'||v==='close')){state.flags['open:'+o.id]=v==='close'?false:!isOpen(o.id);say(o.name,isOpen(o.id)?'You draw the curtain aside. Rain streaks down the window.':'You close the curtain. The library becomes rather cozy.');render();save();return;}
 if((o.openable||o.id==='cupboard'||o.id==='sideboard')&&(v==='open'||v==='close')){state.flags['open:'+o.id]=v==='open';const text=v==='close'?'You close it carefully.':o.id==='cupboard'?'You open the cupboard. An unlit storm lamp rests on the lower shelf. TAKE it.':o.id==='sideboard'?'The drawer slides open. A box of dry matches lies beneath the cutlery. TAKE it.':o.inside;say(o.name,text);if(v==='open')note(o.name+': '+text);audio.play('door');render();save();return;}
 if(v==='talk')say(o.name,'You address '+o.name.toLowerCase()+'. It remains impressively furniture-like. A kitten might make better conversation.');else if(v==='push'||v==='pull')say(o.name,'You try to '+v+' '+o.name.toLowerCase()+'. It is fixed in place. Look for wheels, hinges, or scrape marks.');else if(v==='open'||v==='close')say(o.name,'There is no accessible lid or door here. LOOK for a seam or a drawer.');else if(v==='take')say(o.name,'It is too large for your pockets. Smaller things are easier to TAKE.');else if(v==='pet')say(o.name,'Pleasant texture. No purr. Try a kitten.');else say(o.name,'Nothing happens yet. Select an inventory item, then USE it with a fitting object.');
}
function travel(id,dir){if(id==='cellar'&&(!state.flags.cellarUnlocked||!state.flags.lampLit)){say('Cellar gate',!state.flags.cellarUnlocked?'The gate is locked. USE the brass cellar key on the stairs.':'The stairs disappear into darkness. Fill the lamp with oil, then light it with matches or at the stove.');audio.play('locked');return;}if(id==='vault'&&!state.won){act(scene.find(o=>o.id==='nurseryDoor'),'open');return;}route=[];arrival=null;pendingMove=null;state.room=id;const d=opposite[dir]||'s',[x,y]=doors[d];state.x=d==='w'?1:d==='e'?56:x;state.y=d==='n'?2:d==='s'?20:y;if(!state.visited.includes(id))state.visited.push(id);audio.setRoom(id);say(rooms[id].name,rooms[id].flavor);audio.play('door');render();save();}
function finish(){state.won=true;note('Found Button. All nine kittens are safe.');travel('vault','n');$('ending-stats').textContent=milestones.filter(([f])=>state.flags[f]).length+' discoveries. '+state.pets+' pets given.';$('ending').showModal();audio.stopEffects();audio.play('ending');audio.speak('In a nest of blue scarves sleeps Button. All nine kittens are safe. Some secrets just need a nap.');save();}
function catTarget(c){return {...c,...pos[c.id],cat:true,art:[c.glyph]};}
function targetAt(x,y){const cat=cats.find(c=>c.room===state.room&&pos[c.id].x===x&&pos[c.id].y===y);if(cat)return catTarget(cat);const direct=grid[y]?.[x]?.object;if(direct)return direct;return [...scene].reverse().find(o=>x>=o.x&&y>=o.y&&x<o.x+Math.max(...o.art.map(r=>r.length))&&y<o.y+o.art.length)||null;}
function distanceTo(o,x,y){const width=Math.max(...o.art.map(r=>r.length)),height=o.art.length;return Math.max(o.x-x,0,x-(o.x+width-1))+Math.max(o.y-y,0,y-(o.y+height-1));}
function pathTo(x,y,target=null){const start=[state.x,state.y],q=[start],seen=new Set([start.join(',')]),prev=new Map();let end=null;for(let i=0;i<q.length;i++){const[a,b]=q[i];if(target?distanceTo(target,a,b)<=2:a===x&&b===y){end=[a,b];break;}for(const[dx,dy]of [[0,-1],[1,0],[0,1],[-1,0]]){const nx=a+dx,ny=b+dy,key=nx+','+ny,cell=grid[ny]?.[nx];if(!cell||cell.solid||seen.has(key))continue;if(cell.object?.to&&!(nx===x&&ny===y)&&!target?.to)continue;if(cats.some(c=>c.room===state.room&&pos[c.id].x===nx&&pos[c.id].y===ny))continue;seen.add(key);prev.set(key,[a,b]);q.push([nx,ny]);}}if(!end)return null;const out=[];while(end[0]!==start[0]||end[1]!==start[1]){out.unshift(end);end=prev.get(end.join(','));}return out;}
function approach(o,v=verb){if(v==='look'||v==='talk'){act(o,v);return;}const p=pathTo(o.x,o.y,o);if(!p){feedback('That object is out of reach from here. Try approaching its other side.');return;}pendingMove=null;route=p;arrival=()=>act(scene.find(t=>t.id===o.id)||(o.cat?catTarget(cats.find(c=>c.id===o.id)):o),v);if(!route.length){const f=arrival;arrival=null;f();}}
function move(dx,dy){if(panel!=='play'||hasDialog()||playerMotion.busy())return false;const x=state.x+dx,y=state.y+dy,cell=grid[y]?.[x];if(!cell||cell.solid||cats.some(c=>c.room===state.room&&pos[c.id].x===x&&pos[c.id].y===y)){audio.play('wall');return false;}if(cell.object?.to){travel(cell.object.to,cell.object.dir);return true;}playerMotion.stepTo(x,y);state.x=x;state.y=y;state.steps++;if(!playerMotion.enabled)audio.play('step');render();save();return true;}
function tileFromEvent(e){const svg=$('screen').querySelector('svg'),r=svg.getBoundingClientRect();return window.BrambleVisuals.unproject((e.clientX-r.left)*1000/r.width,(e.clientY-r.top)*660/r.height);}
function eventTarget(e){const g=e.target.closest?.('[data-target]');if(!g)return null;const id=g.getAttribute('data-target');const object=scene.find(o=>o.id===id);if(object)return object.key&&!['use','look'].includes(verb)?scene.find(o=>o.id==='piano'):object;return (()=>{const c=cats.find(t=>t.id===id);return c?catTarget(c):null;})();}
$('screen').onpointermove=e=>{hover=eventTarget(e);updateVerb();};$('screen').onpointerleave=()=>{hover=null;updateVerb();};
function sceneClick(e){if(hasDialog())return;const target=eventTarget(e);if(target){if(verb==='walk'&&target.to){approach(target,'open');return;}if(verb!=='walk'){approach(target);return;}}const{x,y}=tileFromEvent(e);if(x<1||x>=W-1||y<1||y>=H-1)return;if(verb==='walk'){const p=pathTo(x,y);if(p){pendingMove=null;route=p;arrival=null;}else feedback('That spot is blocked.');return;}const floorTarget=targetAt(x,y);if(floorTarget)approach(floorTarget);else say('The house',verb==='look'?'Translucent planes, colored shadows, and the occasional pawprint. Try looking at the furniture.':'The floor keeps its secrets. Try an object in the room.');}
$('screen').onclick=sceneClick;$('screen').addEventListener('keydown',e=>{if(e.key!=='Enter')return;const o=eventTarget(e);if(o){e.preventDefault();approach(o);}});
function renderRoomObjects(){const root=$('room-objects');root.replaceChildren();const targets=[...scene.filter(o=>!o.to),...cats.filter(c=>c.room===state.room).map(c=>(catTarget(c)))];for(const o of targets){const b=document.createElement('button');b.textContent=o.name;b.onpointerenter=()=>{hover=o;updateVerb();};b.onpointerleave=()=>{hover=null;updateVerb();};b.onclick=()=>approach(o);root.append(b);}}
function setPanel(name){panel=name;route=[];arrival=null;pendingMove=null;audio.stopSpeech();for(const n of ['play','inventory','journal','atlas'])$(n+'-panel').hidden=n!==name;document.querySelectorAll('nav [data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===name));if(name==='inventory')renderInventoryPanel();if(name==='journal')renderJournal();if(name==='atlas')renderAtlas();}
function renderInventoryPanel(){const root=$('inventory-details');root.replaceChildren();for(const id of state.items){const entry=document.createElement('div');entry.className='entry';const art=document.createElement('div');art.innerHTML=window.BrambleVisuals.icon(id);const h=document.createElement('h3');h.textContent=items[id].name;const p=document.createElement('p');p.textContent=id==='lamp'?(state.flags.lampLit?'Filled and lit. Ready for the cellar.':state.flags.lampFilled?'Filled with oil, awaiting a flame.':items[id].look):items[id].look;const b=document.createElement('button');b.textContent='Use this item ↗';b.onclick=()=>{setPanel('play');held=id;verb='use';render();};entry.append(art,h,p,b);root.append(entry);}if(!state.items.length)root.textContent='Your pockets are empty. Use LOOK, OPEN, PUSH, and TAKE to find useful things.';}
function renderJournal(){const root=$('journal-entries');root.replaceChildren();for(const text of state.notes){const e=document.createElement('div');e.className='entry';const p=document.createElement('p');p.textContent=text;e.append(p);root.append(e);}if(!state.notes.length)root.textContent='No observations yet. Look closely at the family portrait in the foyer.';}
function renderAtlas(){const root=$('room-directory');root.replaceChildren();const nodes={foyer:[390,385],hall:[390,275],library:[205,275],conservatory:[205,165],dining:[575,275],kitchen:[575,165],gallery:[390,165],music:[30,55],bedroom:[750,165],attic:[390,55],cellar:[575,385],vault:[750,385]};let art='<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 910 455" aria-label="Connected rooms of Bramble House">';const edges=new Set();for(const[id,r]of Object.entries(rooms)){for(const to of Object.values(r.exits)){const key=[id,to].sort().join('-');if(edges.has(key))continue;edges.add(key);const[a,b]=nodes[id],[c,d]=nodes[to];art+='<path d="M'+(a+65)+' '+(b+25)+'L'+(c+65)+' '+(d+25)+'" fill="none" stroke="#3b9ebc" stroke-opacity=".25" stroke-width="2"/>';}}art+='<path d="M455 190 L640 410" fill="none" stroke="#dc6c64" stroke-opacity=".35" stroke-dasharray="3 5"/>';let n=0;for(const[id,r]of Object.entries(rooms)){const[x,y]=nodes[id],seen=state.visited.includes(id),c=['#3b9ebc','#dc6c64','#9a86bd','#75ab8c'][n++%4];art+='<g class="ink" opacity="'+(seen?1:.4)+'"><rect x="'+x+'" y="'+y+'" width="130" height="52" rx="3" fill="'+c+'" fill-opacity=".15" stroke="'+c+'" stroke-opacity=".45"/><text x="'+(x+65)+'" y="'+(y+29)+'" font-size="11" text-anchor="middle">'+(seen?r.name.replace(/^The /,''):'Unexplored')+'</text></g>';}art+='</svg>';$('atlas-art').innerHTML=art;for(const[id,r]of Object.entries(rooms)){const b=document.createElement('button');b.textContent=state.visited.includes(id)?r.name+' ↗':'Unexplored · '+r.floor.toLowerCase();b.disabled=!state.visited.includes(id);b.onclick=()=>{setPanel('play');state.room=id;state.x=29;state.y=20;audio.setRoom(id);say(r.name,'You return along a familiar route. '+r.flavor);render();save();};root.append(b);}}
function audioControls(){const p=audio.prefs;$('voice').textContent=audio.canSpeak?'Voice '+(p.voice?'on':'off'):'Voice unavailable';$('voice').disabled=!audio.canSpeak;$('voice').setAttribute('aria-pressed',String(p.voice&&audio.canSpeak));$('sound').textContent='Sound '+(p.sfx?'on':'off');$('sound').disabled=!audio.canSound;$('sound').setAttribute('aria-pressed',String(p.sfx&&audio.canSound));$('volume-level').textContent=Math.round(p.volume*100)+'%';}
function replay(){const cat=lastTarget?.cat?cats.find(c=>c.id===lastTarget.id):cats.find(c=>$('speaker').textContent===c.name);if(cat)audio.catDialogue($('dialogue').textContent,cat.id);else audio.speak($('dialogue').textContent);}
$('voice').onclick=()=>{audio.set('voice',!audio.prefs.voice);audioControls();if(audio.prefs.voice)replay();};$('sound').onclick=()=>{audio.set('sfx',!audio.prefs.sfx);audioControls();if(audio.prefs.sfx)audio.play('meow','pip');};$('replay-voice').onclick=replay;$('volume-down').onclick=()=>{audio.volume(-.1);audioControls();};$('volume-up').onclick=()=>{audio.volume(.1);audioControls();};window.addEventListener('ascicat-audio-status',audioControls);
const bar=$('verbs');for(const v of verbs){const b=document.createElement('button');b.dataset.verb=v;b.textContent=({look:'Look at',talk:'Talk to'}[v]||v[0].toUpperCase()+v.slice(1));b.onclick=()=>selectVerb(v);bar.append(b);}
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>setPanel(b.dataset.panel));document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{route=[];arrival=null;pendingMove=null;move(...b.dataset.move.split(',').map(Number));});
$('interact').onclick=()=>{const targets=[...scene,...cats.filter(c=>c.room===state.room).map(c=>(catTarget(c)))].map(o=>({o,d:distanceTo(o,state.x,state.y)})).filter(t=>t.d<=2).sort((a,b)=>a.d-b.d);if(targets[0])act(targets[0].o);else feedback('Select a verb and click an object in the room.');};$('pet').onclick=()=>{const c=cats.find(c=>c.room===state.room&&Math.abs(pos[c.id].x-state.x)+Math.abs(pos[c.id].y-state.y)<=3);if(c)pet(c);else feedback('Choose PET and click a kitten.');};
$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();$('restart').onclick=()=>$('confirm-dialog').showModal();$('cancel-restart').onclick=()=>$('confirm-dialog').close();$('confirm-restart').onclick=()=>{state=fresh();held=null;lastTarget=null;cats.forEach(c=>pos[c.id]={x:c.x,y:c.y});$('confirm-dialog').close();setPanel('play');render();save();$('intro').showModal();};
function start(){audio.unlock();state.started=true;$('intro').close();save();say('Bramble House','Nine kittens live here. Only eight came to dinner. Look behind portraits, open cupboards, and listen to the kittens.');}$('start').onclick=start;$('keep-playing').onclick=()=>$('ending').close();$('intro').addEventListener('cancel',e=>{e.preventDefault();start();});
document.addEventListener('pointerdown',()=>audio.unlock(),{passive:true});document.addEventListener('keydown',e=>{audio.unlock();if(e.target.matches('input,textarea,select'))return;if(hasDialog()){if(e.key==='Enter'&&$('intro').open)start();return;}const k=e.key.toLowerCase(),moves={w:[0,-1],arrowup:[0,-1],s:[0,1],arrowdown:[0,1],a:[-1,0],arrowleft:[-1,0],d:[1,0],arrowright:[1,0]};if(moves[k]){e.preventDefault();route=[];arrival=null;pendingMove=playerMotion.busy()?moves[k]:null;if(!pendingMove)move(...moves[k]);}else if(['1','2','3','4'].includes(k))setPanel(['play','inventory','journal','atlas'][+k-1]);else if(k==='escape'){held=null;selectVerb('look');setPanel('play');}else if(k==='e'||k===' '){e.preventDefault();$('interact').onclick();}else if(k==='p')$('pet').onclick();else if(k==='l')selectVerb('look');else if(k==='o')selectVerb('open');else if(k==='t')selectVerb('talk');});
setInterval(()=>{if(!state.started||hasDialog()||document.hidden||panel!=='play')return;if(playerMotion.busy())return;if(pendingMove){const direction=pendingMove;pendingMove=null;move(...direction);return;}if(route.length){const[nx,ny]=route.shift();if(Math.abs(nx-state.x)+Math.abs(ny-state.y)!==1||!move(nx-state.x,ny-state.y)){route=[];arrival=null;pendingMove=null;}}if(!route.length&&arrival&&!playerMotion.busy()){const f=arrival;arrival=null;f();}},45);
setInterval(()=>{if(!state.started||hasDialog()||document.hidden)return;state.seconds++;seconds++;$('clock').textContent=String(Math.floor(state.seconds/60)).padStart(2,'0')+':'+String(state.seconds%60).padStart(2,'0');if(panel==='play'&&!route.length){if(seconds%8===0&&!audio.isTalking&&Math.random()<.6){const c=cats.filter(c=>c.room===state.room);if(c.length)audio.play('meow',c[Math.floor(Math.random()*c.length)].id);}if(seconds%3===0&&!audio.isTalking){for(const c of cats.filter(c=>c.room===state.room)){if(Math.random()>.75)continue;const p=pos[c.id],[dx,dy]=[[0,1],[0,-1],[1,0],[-1,0]][Math.floor(Math.random()*4)],x=p.x+dx,y=p.y+dy;if(grid[y]?.[x]&&!grid[y][x].solid&&!grid[y][x].object&&Math.abs(x-c.x)<=3&&Math.abs(y-c.y)<=2&&Math.abs(x-state.x)+Math.abs(y-state.y)>2){p.fromX=p.x;p.fromY=p.y;p.moveStarted=Date.now();p.movingUntil=p.moveStarted+(reducedMotion?.matches?0:850);p.x=x;p.y=y;}}render();}if(seconds%15===0&&!audio.isTalking)audio.play('creak');}if(seconds%10===0)save();},1000);
// Animate actors between logical tiles without rebuilding the room each frame.
function animateActors(){
 if(state.started&&panel==='play'&&!document.hidden&&!hasDialog()){
  const now=Date.now();
  const playerActor=$('screen').querySelector('.player');
  const pose=playerMotion.sample(now);
  if(playerActor)playerActor.innerHTML=Player.draw(state.playerStyle,pose);
  if(playerMotion.drainFootfalls())audio.play('step');
  for(const actor of $('screen').querySelectorAll('[data-cat-id]')){
   const p=pos[actor.getAttribute('data-cat-id')],offset=window.BrambleVisuals.catOffset(p,now);
   actor.setAttribute('transform','translate('+offset.join(' ')+')');
   actor.querySelector('.cat-shape')?.classList.toggle('is-walking',now<(p.movingUntil||0));
  }
 }
 requestAnimationFrame(animateActors);
}
if(typeof requestAnimationFrame==='function')requestAnimationFrame(animateActors);
$('intro-art').innerHTML=window.BrambleVisuals.cover();$('ending-art').innerHTML=window.BrambleVisuals.cover();
window.addEventListener('pagehide',()=>{save();audio.stopSpeech();audio.stopEffects();});audio.setRoom(state.room);audioControls();render();if(!state.started)$('intro').showModal();else say(rooms[state.room].name,'Welcome back. '+rooms[state.room].flavor);
})();
