const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const repo=path.join(__dirname,'..');
class El{constructor(id){this.id=id;this.listeners={};this.hidden=false;this.open=false;this.value='';this.textContent='';this.innerHTML='';this.dataset={};this.children=[];this.classList={toggle(){}};}addEventListener(n,f){this.listeners[n]=f;}setAttribute(){}replaceChildren(...c){this.children=c;}append(...c){this.children.push(...c);}showModal(){this.open=true;}close(){this.open=false;}focus(){}matches(){return false;}querySelectorAll(){return [];}querySelector(){return null;}}
const elements={};for(const m of fs.readFileSync(path.join(repo,'index.html'),'utf8').matchAll(/id="([^"]+)"/g))elements[m[1]]=new El(m[1]);
const panels=['play','inventory','journal','atlas'].map(n=>{const e=new El();e.dataset.panel=n;return e;}),moves=['0,-1','-1,0','0,1','1,0'].map(n=>{const e=new El();e.dataset.move=n;return e;});
const storage=new Map(),timers=new Map();let timerId=0;const sandbox={document:{hidden:false,getElementById:id=>elements[id],querySelectorAll:q=>q.includes('data-verb')?elements.verbs.children:q.includes('move')?moves:panels,querySelector:()=>Object.values(elements).find(e=>e.open),createElement:tag=>new El(tag),addEventListener(){}},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},window:{addEventListener(){}},setInterval(){},setTimeout:f=>{timers.set(++timerId,f);return timerId;},clearTimeout:id=>timers.delete(id),console};
for(const f of ['audio.js','adventure-data.js','geometry.js','player.js','visuals.js'])vm.runInNewContext(fs.readFileSync(path.join(repo,f),'utf8'),sandbox);
let code=fs.readFileSync(path.join(repo,'game.js'),'utf8').replace(/\}\)\(\);\s*$/,`window.test={get state(){return state},get scene(){return scene},get grid(){return grid},rooms,cats,render,objectsFor,pathTo,travel,act,acquire,inventoryClick,selectVerb,useItem,start,flag,pos};})();`);vm.runInNewContext(code,sandbox);const t=sandbox.window.test;t.start();
const object=id=>t.scene.find(o=>o.id===id),action=(id,v)=>{assert(object(id),'missing object '+id);if(v==='take'&&object(id).item)assert.equal(t.grid[object(id).y][object(id).x].object?.id,id,'revealed item must be visible');t.act(object(id),v);};
function room(id){t.state.room=id;t.state.x=29;t.state.y=20;t.render();}
function reachable(){for(const id of Object.keys(t.rooms)){room(id);for(const o of t.scene){const p=t.pathTo(o.x,o.y,o);assert(p!==null,id+': unreachable '+o.id);}assert(!/NaN|undefined/.test(elements.screen.innerHTML),id+': invalid SVG coordinates');for(const o of t.scene)assert(elements.screen.innerHTML.includes('data-target="'+o.id+'"'),id+': missing graphical hotspot '+o.id);assert.equal(t.grid.length,23);assert(t.grid.every(r=>r.length===58));}}
reachable();room('foyer');action('familyPortrait','pull');assert(t.state.flags.portraitLifted);action('item:crank','take');assert(t.state.items.includes('crank'));
room('library');action('bookcase','push');action('item:oil','take');assert(t.state.flags.bookcaseMoved);action('bookcase','pull');assert(!t.state.flags.bookcaseMoved);action('bookcase','push');
room('kitchen');action('cupboard','open');action('item:lamp','take');t.useItem('matches',{id:'inventory:lamp',item:'lamp',name:'Lamp'});assert(!t.state.flags.lampLit,'dry lamp must not light');t.useItem('oil',{id:'inventory:lamp',item:'lamp',name:'Lamp'});assert(t.state.flags.lampFilled);
room('dining');action('sideboard','open');action('item:matches','take');t.selectVerb('use');t.inventoryClick('matches');t.inventoryClick('lamp');assert(t.state.flags.lampLit);
room('gallery');assert(!t.state.flags.portraitsAligned);for(let i=0;i<2;i++)action('westPortrait','push');for(let i=0;i<2;i++)action('centerPortrait','pull');for(let i=0;i<2;i++)action('eastPortrait','push');assert.equal(t.state.orientations.join(','),'1,0,3');assert(t.state.flags.portraitsAligned);action('item:key','take');
room('conservatory');action('bench','use');assert(!t.state.flags.hookReached);action('bench','push');action('bench','use');action('item:hook','take');assert(t.state.items.includes('hook'));
room('music');action('piano','open');assert(!t.state.flags['open:piano']);action('eyeKey','use');assert(!t.state.flags.melodySolved);action('moonKey','use');action('eyeKey','use');action('whiskerKey','use');assert(t.state.flags.melodySolved);action('piano','open');action('item:weight','take');
room('gallery');action('stairs','open');assert.equal(t.state.room,'gallery','still locked');t.useItem('key',object('stairs'));action('stairs','open');assert.equal(t.state.room,'cellar');action('nurseryDoor','open');assert(!t.state.won);t.useItem('hook',object('highLatch'));assert(!t.state.flags.latchReleased);action('crate','push');assert.equal(t.state.crate,0);t.useItem('crank',object('crate'));for(let i=0;i<3;i++)action('crate','push');assert(t.state.flags.crateOnPlate);action('crate','pull');assert(!t.state.flags.crateOnPlate);action('crate','push');t.useItem('weight',object('chain'));assert(t.state.flags.chainBalanced);t.useItem('hook',object('highLatch'));assert(t.state.flags.latchReleased);action('nurseryDoor','open');assert(t.state.won);assert.equal(t.state.room,'vault');assert(elements.ending.open);assert(JSON.parse(storage.get('ascicat.adventure.v2')).won);
reachable();assert.equal(elements.verbs.children.length,10);assert(!code.includes('cipher('));assert(!fs.readFileSync(path.join(repo,'index.html'),'utf8').includes('decode-form'));
for(let x=0;x<58;x+=3)for(let y=0;y<23;y+=2){const q=sandbox.window.BrambleVisuals.project(x,y),r=sandbox.window.BrambleVisuals.unproject(...q);assert.equal(r.x,x);assert.equal(r.y,y);}
console.log('PASS: every room hotspot reachable before/after changes, all ten verbs, graphical hotspots in every room, projection/hit-test round trips, full environmental puzzle chain, blocked premature attempts, reversible furniture/plate, item combinations, complete ending and save.');
